project:
  type: website

website:
  title: "Yadu Vasudev"
  search: false
  google-analytics: G-MN1T4J4SRB
  navbar: 
    left:
      - text: Research
        menu:
          - text: Publications
            href: research.qmd
          - text: People
            href: people.qmd
      - href: courses.qmd
        text: Teaching
      - text: Contact
        href: contact.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    header-includes: |
      <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Ubuntu" type="text/css"/>
    mainfont: 'Ubuntu'
    fontsize: 1em
    margin-left: 10px



