project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  title: "Yadu Vasudev"
  search: false
  google-analytics: G-MN1T4J4SRB
  navbar: 
    left:
      - text: Research
        menu:
          - text: Publications
            href: research.qmd
          - text: People
            href: people.qmd
      - href: courses.qmd
        text: Teaching
      - text: Contact
        href: contact.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    mainfont: 'Lato'
    fontsize: 1.1em



