---
title: "CS5800 Advanced Data Structures & Algorithms"
subtitle: Jul - Nov 2024
page-layout: full
lightbox: true
listing:
  - id: lectures
    type: table
    contents: lectures.yml
    template: lectures.ejs
    page-size: 100
include-in-header: 
  - text: |
      <style>
      .panel-tabset > .nav-tabs,
      .panel-tabset > .tab-content{
        border:none;
      }

      .nav-pills .nav-item{
        margin-left: 5px;
        margin-right: 5px;
      }

      .nav-pills .nav-link {
        background-color: #ccf7f1;
        border-radius: 3px;
      }

      .nav-pills .nav-link.active{
        background-color: #ffdd00; 
        color: #1c1c1c;
        border-radius: 3px;
      }
      
      .nav-pills .nav-link:hover {
        text-decoration: underline dotted;
        color: #0F096A;
      }

      </style>
---

::: nav-pills
::: panel-tabset

## about

::: {.grid}

::: {.g-col-6}

####  {{< bi compass color=#40CB2D >}} Coordinates

- Where: CS15
- When: D slot - Mon (11 am), Tue (10 am), Wed (9 am), Thu (12 pm)


#### {{< bi person-fill color=#40CB2D >}} Instructor
- [Yadu Vasudev](https://yaduvasudev.github.io/)
- SSB 207
- yadu@cse.iitm.ac.in

#### {{< bi people-fill color=#40CB2D >}} TAs
- Aditya (cs22s005@smail)
- Arun (cs23m017@smail)
- Nagashri (cs21d004@smail)
- Narayana (cs22s004@smail)
- Sampriti (cs18d200@smail)
- Subramanian (cs23m067@smail)
- Vasu (cs23m072@smail)
- Vasuki (cs22d013@smail)

:::

::: {.g-col-6}

#### {{< bi link-45deg color=#40CB2D >}} Important links

- [Moodle](https://courses.iitm.ac.in/course/view.php?id=4902) 
- [Ed Discussions](https://edstem.org/us/courses/61145/discussion/) (for discussions, Q/A, announcements) \
  Join using your smail/iitm ids via [this link](https://edstem.org/us/join/MQYjkx)
- [Anonymous course feedback](https://forms.gle/st9ZZtom2DkzviV99)

:::

:::


## contents

::: {.grid}

::: {.g-col-10}

#### {{< bi body-text color=#40CB2D >}} About this course

This is a basic graduate-level course that introduces some advanced data structures, algorithm design techniques. There will be a lot of emphasis on reasoning about the data structures and algorithms that you design, and formally proving the correctness of constructions. 

**Prerequisites** - A basic course in design and analysis of algorithms is necessary. The course will require you to design data structures and algorithms, and then mathematically prove their correctness. There **will not be any programming component** for this course, though you may be required to implement a few of the data structures and algorithms in CS6150 (Advanced Programming Lab).
---

#### {{< bi card-list color=#40CB2D >}} Course contents

The following is a brief overview of the topics that will be covered in this course. The order of the topics covered may vary.

- Basic principles from algorithm design - asymptotic analysis, amortized analysis, randomization
- Data structures 
  - Dictionary ADT - hash tables, skip lists, binary search trees
  - Priority Queue ADT - binary heaps, min-max heaps, mergeable heaps
  - Disjoint set ADT and applications
- Algorithm design
  - Greedy algorithms - scheduling, Huffman coding, MST
  - Dynamic programming - DP on strings, trees, DAGs, and graphs
  - Network flows and applications
- Intractability 
  - Notion of poly-time reductions
  - NP-completeness and its consequences
  - Coping with intractability
  
---

#### {{< bi book-fill color=#40CB2D >}} Course resources

There are many textbooks and resources (both offline and online) that cover most of the material presented in the list above. We will not be following one textbook. Our main sources of reference will be the following textbooks.

- **[E]** - [Algorithms](https://jeffe.cs.illinois.edu/teaching/algorithms/book/Algorithms-JeffE.pdf) by Erickson
- **[CLRS]** - Introduction to Algorithms by Cormen, Leiserson, Rivest, and Stein, 3rd Edition
- **[M]** - [Open Data Structures](https://opendatastructures.org/) by Morin
- **[DPV]** - Algorithms by Dasgupta, Papadimitriou, and Vazirani

All these books contain a number of exercise problems for practice.

:::

:::

## administrivia

::: {.grid}

::: {.g-col-10}

#### {{< bi clock-fill color=#40CB2D >}} Weekly schedule

There will be four lectures every week, some of which will be converted to tutorial/problem-solving sessions. I will be releasing problem sets regularly which will be discussed in the tutorial sessions. You can also use the course discussion forum to discuss these with your peers and the course staff.

---

#### {{< bi percent color=#40CB2D >}} Grading policy (tentative)

The course will be graded based on a number of tests. The following is a tentative grading policy. **There will be no make-up for the tutorial tests**.

- Open-book tutorial tests: Best 2 out of 3 - **2 * 15 = 30%**
- Quizzes - **2 * 15 = 30%**
- End-semester exam - **40%**
---

#### {{< bi calendar-fill color=#40CB2D >}} Important dates (tentative)

We will stick to this schedule as much as possible, unless there are some unforeseen situations.

::: {.callout-tip appearance="simple"}

 - Problem solving sessions: Aug 14, Sep 19, Oct 24
 - Open-book tutorial tests: Aug 22, Sep 26, Oct 30
 - Quizzes: Sep 2, Oct 10
 - End-semester exam: Nov 20

::: 

---

#### {{< bi chat-dots-fill color=#40CB2D >}} Communication

Please sign up on the course discussion forum [here](https://edstem.org/us/join/MQYjkx). This will be the first point of contact for any issues related to the course. For general questions related to the course (any comments/doubts), please create a thread in the correct category and add your question/comment there. You are encouraged to reply and clear the doubts of your friends. To encourage this interaction, **the forum supports anonymous posts and answers**. **Please be courteous to others when you are posting anonymously**.

:::

:::

## lectures

::: {#lectures}


:::

:::

:::
